modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="uncrafting_table"
version="1.0.0"
displayName="拆解台"
# logoFile="pack.png"
authors="Xiaoyu_2009"
displayURL="https://space.bilibili.com/506597031"
description='''
拆解台模组 - 从暮色森林移植
'''

[[dependencies.uncrafting_table]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.uncrafting_table]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"